### ISSUE TITLE
myq adapter can't connect

### ISSUE THREAD

**Issue by firechhe** [StrathCole/ioBroker.myq#2]
Hello,

Since 2 or 3 days the myq ioBroker adapter can't connect to myq. Here is the log from ioBroker:

`

  |   |   |  
-- | -- | -- | --
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | info | Restart adapter system.adapter.myq.0 because enabled
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | info | instance system.adapter.myq.0 terminated with code 0 (NO_ERROR)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (E:\ioBroker\SmartHome\node_modules\request\request.js:1083:12)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at Request.<anonymous> (E:\ioBroker\SmartHome\node_modules\request\request.js:1161:10)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.834 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.833 | error | Caught by controller[0]: at Request.self.callback (E:\ioBroker\SmartHome\node_modules\request\request.js:185:22)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.833 | error | Caught by controller[0]: at Request._callback (E:\ioBroker\SmartHome\node_modules\iobroker.myq\lib\myq.js:102:32)
host.HomeServer(SmartHome) | 2020-07-06 16:58:51.833 | error | Caught by controller[0]: TypeError: controller.context.stop is not a function
myq.0 | 2020-07-06 16:58:51.297 | info | (1220) Terminated (NO_ERROR): Without reason
myq.0 | 2020-07-06 16:58:51.297 | info | (1220) terminating
myq.0 | 2020-07-06 16:58:51.290 | error | (1220) TypeError: controller.context.stop is not a function at Request._callback (E:\ioBroker\SmartHome\node_modules\iobroker.myq\lib\myq.js:102:32) at Request.self.callback (E:\ioBroker\Smart
myq.0 | 2020-07-06 16:58:51.289 | error | (1220) uncaught exception: controller.context.stop is not a function
myq.0 | 2020-07-06 16:58:51.284 | warn | (1220) Login failed.
myq.0 | 2020-07-06 16:58:50.712 | info | (1220) [INFO] Configured polling interval: 10000
myq.0 | 2020-07-06 16:58:50.705 | info | (1220) [START] Starting MyQ adapter
myq.0 | 2020-07-06 16:58:50.693 | info | (1220) starting. Version 0.1.2 in E:/ioBroker/SmartHome/node_modules/iobroker.myq, node: v10.17.0

`

**Comment by StrathCole** [comment]
I have now switched to myq-api library. This means all states change. Please do:

* stop myq adapter
* delete the whole device tree from the myq.0 tree
* install new version from git
* start myq adapter

**Comment by dietlman** [comment]
Cool it works now! Thanks a lot!
