### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by denzel1994** [StrathCole/ioBroker.myq#3]
For a couple of days i get the message from the adapter that the Login failed.

Login credentials haven’t changed tho.

**Comment by firechhe** [comment]
Hi,
I have the same problem. Login details haven't changed. I got these errors in my log:

`

host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (E:\ioBroker\SmartHome\node_modules\request\request.js:1083:12)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.439 | error | Caught by controller[0]: at Request.<anonymous> (E:\ioBroker\SmartHome\node_modules\request\request.js:1161:10)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.438 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.438 | error | Caught by controller[0]: at Request.self.callback (E:\ioBroker\SmartHome\node_modules\request\request.js:185:22)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.438 | error | Caught by controller[0]: at Request._callback (E:\ioBroker\SmartHome\node_modules\iobroker.myq\lib\myq.js:102:32)
host.HomeServer(SmartHome) | 2020-10-06 22:37:13.438 | error | Caught by controller[0]: TypeError: controller.context.stop is not a function

`

Hope that the developer can fix this problem.

**Comment by stiefen** [comment]
Same problem here - is anyone able to help?

Thanks in advance

**Comment by StrathCole** [comment]
See https://github.com/StrathCole/ioBroker.myq/issues/2#issuecomment-724624190
